<a href="https://colab.research.google.com/github/kimayeon-hub/DeepLearning1/blob/main/Python/Week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 배열

- array([]) 사용
- zeros(()) 사용: 0으로 초기화 시켜서 만들어 줌
  - 첫 번째 매개변수: 1차원
  - 두 번째 매개변수: 2차원
  - ...
  
    > 이걸 공간상에서 이해하려고 하면 힘듦 <br>

    > n[몸무게, 키, 성적, 거주지] => n[10, 15, 5, 4] <br>
    > 몸무게 값: 10개, 키 값: 15개, 성적 값: 5개, 거주지 값: 4개인 배열이 만들어진 것

- ones(()): 1로 초기화 시켜서 만들어 줌

> 4차원까지는 만들어서 사용함 <br>
> 그 이상은 이해하기 어려움

In [1]:
import numpy as np

In [4]:
# n이라는 화살표가 변수 np.array([])를 가리킨다고 생각하면 됨
n = np.array([[3, 4, 1, 2],
             [8, 2, 4, 9]])
n

array([[3, 4, 1, 2],
       [8, 2, 4, 9]])

In [6]:
n = np.zeros((3, 5))  # 2차원 배열이 만들어진 것
n

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
n = np.zeros((3, 5, 2)) # 3차원 배열이 만들어진 것
n

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [8]:
n = np.ones((3, 5))
n

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# numpy random
- random.rand()
  - 배열처럼 인덱스를 사용해서 특정 위치의 값을 변경할 수 있음

In [9]:
n = np.random.rand(3, 5)
n

array([[0.78537508, 0.43745681, 0.86566209, 0.60314061, 0.14159756],
       [0.61122571, 0.79500884, 0.28891555, 0.59906063, 0.30515369],
       [0.26032428, 0.77847019, 0.52035949, 0.6316532 , 0.78667177]])

In [10]:
n = np.random.rand(3, 5)
n[0, 0] = 0
n

array([[0.        , 0.50038235, 0.11665831, 0.13824149, 0.01298664],
       [0.68520156, 0.12282253, 0.6169001 , 0.93089441, 0.57932456],
       [0.9382301 , 0.54658351, 0.03231708, 0.13145971, 0.66281967]])

### 실제 사용법
boolean 배열을 만들어서 True인 부분의 값을 0으로 변경하기

In [12]:
import numpy as np

n = np.array([[3, 4, 1, 2], [8, 2, 4, 9], [2, 1, 8, 7]])
b = np.array([[True, False, True, False],
              [True, False, True, False],
              [True, False, True, False]])
n[b] = 0  # b가 만족하는 것을 다 0으로 바꿔라
n

array([[0, 4, 0, 2],
       [0, 2, 0, 9],
       [0, 1, 0, 7]])

In [13]:
n = np.array([[3, 4, 1, 2], [8, 2, 4, 9], [2, 1, 8, 7]])
b = n < 5 # 5보다 작은 경우는 True가 되고, 5보다 큰 경우는 False가 됨

n[b] = 0  # 5보다 작은 값은 다 0으로 바꿔라
n

array([[0, 0, 0, 0],
       [8, 0, 0, 9],
       [0, 0, 8, 7]])

In [16]:
n = np.array([[3, 4, 1, 2], [8, 2, 4, 9], [2, 1, 8, 7]])

n[n > 5] = 5  # 5보다 큰은 값은 다 5로 바꿔라
n

array([[3, 4, 1, 2],
       [5, 2, 4, 5],
       [2, 1, 5, 5]])

# n.shape
- 어떤 배열을 받았을 때, 그 배열의 크기를 모르겠을 때 사용



In [17]:
n = np.array([[3, 4, 1, 2], [8, 2, 4, 9], [2, 1, 8, 7]])
n.shape

(3, 4)

In [19]:
n = np.zeros((2, 4, 3, 5))
n.shape

(2, 4, 3, 5)

In [20]:
n = np.zeros((2, 4, 3, 5))
n.shape[1]

4

In [22]:
n = np.zeros(10)
print(n.shape, n)

(10,) [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 실제 사용법
- 배열을 넘겨 줄 때, 1차원 배열을 2차원으로 바꿔서 보내야 할 떄가 있음 => 차원을 다룰 줄 알아야 함

> zeros(10)과 zeros((10, 1))은 사실상 같은 것임

In [23]:
n = np.zeros(10)
n[3, 0] # 2차원은 당연히 없는 것이므로 엑세스가 안 되는 것

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [24]:
n = np.zeros((10, 1))
n[3, 0]

0.0

# np.reshape(배열, (바꿀 차원))

In [40]:
n = [1, 2, 3, 4, 5, 6, 7, 8]
np.reshape(n, (2, 4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### np.expand_dims()와 비슷하게 사용 가능

In [41]:
k = np.reshape(n, (2, 4, 1))
k.shape

(2, 4, 1)

# np.expand_dims()
- 데이터는 똑같은데 차원을 늘릴 떄 사용

In [25]:
n = np.zeros(10)
n = np.expand_dims(n,1)
n.shape

(10, 1)

In [26]:
n = np.zeros(10)
n = np.expand_dims(n,0) # 차원을 앞에 다가 추가하는 것
n.shape

(1, 10)

In [ ]:
n = np.zeros(10)
n = np.expand_dims(n,-1)  # 차원을 맨 뒤에 추가하는 것
n.shape

# 슬라이싱

In [27]:
n = np.random.rand(3, 4)
n

array([[0.67714524, 0.97490702, 0.30482828, 0.90256789],
       [0.79008267, 0.52230567, 0.74937917, 0.97270067],
       [0.7396214 , 0.73563833, 0.27281203, 0.6779128 ]])

In [28]:
n = np.round(n * 100) # 정수로 바꿈
n

array([[68., 97., 30., 90.],
       [79., 52., 75., 97.],
       [74., 74., 27., 68.]])

In [29]:
n[2,3]

68.0

In [30]:
n[2,:]

array([74., 74., 27., 68.])

In [31]:
n[2, 2:4] # 2번째 행에서 2에서 3까지의 수를 선택

array([27., 68.])

In [32]:
n[1:3, 2:4]

array([[75., 97.],
       [27., 68.]])

In [34]:
n[0:4:2,:]

array([[68., 97., 30., 90.],
       [74., 74., 27., 68.]])

In [35]:
n[:, 2:]

array([[30., 90.],
       [75., 97.],
       [27., 68.]])

In [36]:
n[:, :3]

array([[68., 97., 30.],
       [79., 52., 75.],
       [74., 74., 27.]])

# np.max, np.min

In [42]:
data = np.random.rand(3,5)
data

array([[0.43346337, 0.7911553 , 0.72915208, 0.69173229, 0.43238496],
       [0.03337047, 0.38627688, 0.4762409 , 0.83741306, 0.89753458],
       [0.41396812, 0.24269195, 0.9213211 , 0.53524578, 0.85667329]])

In [43]:
np.max(data)

0.9213210984343498

In [44]:
np.min(data)

0.03337046970131996

In [45]:
np.mean(data, axis=0) # 0번(cloumn) 축을 기준으로 data의 평균을 구하는 것
# 값이 5개가 나오므로 cloumn을 기준으로 평균을 구했다는 것을 알 수 있음

array([0.29360066, 0.47337471, 0.7089047 , 0.68813038, 0.72886428])

In [46]:
np.mean(data, axis=1) # 1번(row) 축을 기준으로 평균을 구하는 것
# 값이 3개가 나오므로 row을 기준으로 평균을 구했다는 것을 알 수 있음

array([0.6155776 , 0.52616718, 0.59398005])

### 연습 (p.184, 186, 187)

In [47]:
data = np.array([[8.5, 200, 60.2, 450.3, 50],
                 [12.3, 230.5, 56.3, 390.2, 35],
                 [9.2, 190, 30, 500.4, 60]])

In [51]:
data[:,1] # 멀리뛰기 값만 보기

array([200. , 230.5, 190. ])

In [52]:
idx = data[:, 1] > 190  # 멀리뛰기가 190 이상인 사람들
data[idx,:]

array([[  8.5, 200. ,  60.2, 450.3,  50. ],
       [ 12.3, 230.5,  56.3, 390.2,  35. ]])

In [53]:
data[data[:, 1] > 190,:]

array([[  8.5, 200. ,  60.2, 450.3,  50. ],
       [ 12.3, 230.5,  56.3, 390.2,  35. ]])

In [50]:
mean_v = np.mean(data, axis=0)
std_v = np.std(data, axis=0)
print(f'50m달리기: {mean_v[0]:.2f} +- {std_v[0]:.2f}')
print(f'멀리뛰기: {mean_v[1]:.2f} +- {std_v[1]:.2f}')
print(f'오래매달리기: {mean_v[2]:.2f} +- {std_v[2]:.2f}')
print(f'오래달리기: {mean_v[3]:.2f} +- {std_v[3]:.2f}')
print(f'윗몸일으키기: {mean_v[4]:.2f} +- {std_v[4]:.2f}')

50m달리기: 10.00 +- 1.65
멀리뛰기: 206.83 +- 17.23
오래매달리기: 48.83 +- 13.41
오래달리기: 446.97 +- 45.05
윗몸일으키기: 48.33 +- 10.27


In [ ]:
data = np.array([1, 2, 5, 0. 1])
idx_max = np.argmax(data)
idx_min = np.argmin(data)
print(f'최솟값은 {data[idx_min]} 입니다.')

# 전역변수, 지역변수
- 파라미터로 들어오는 변수와 전역변수의 변수의 이름이 같으면 코드가 헷갈리게 됨
- 전역변수의 변수 이름과 지역변수의 변수 이름을 다르게 설정하기

In [54]:
a = 3 # 전역변수

In [55]:
def custom_func(d):
  a = a + 1 # 이렇게 코드를 짜는 것은 권장되지 않음
  # 코딩을 하다 보면 헷갈리게 됨
  return a

In [57]:
custom_func(a)

4

In [58]:
a

3